---
title: 'Introducción al análisis de datos biológicos con R'
date: 2021-08-16T14:00:00
date_end: 2021-09-27T17:00:00

categories:
  - R
  - curso
tags:
  - R
  - curso
  - análisis de datos
subtitle: Este es un curso de un mes y medio en programación R para análisis de datos biológicos.
summary: Este es un curso de un mes y medio en programación R para análisis de datos biológicos. Se realiza de forma virtual y contará con una combinación de clases sincrónicas y asincrónicas, con ejercicios que se entregarán semanalmente y una presentación final.
slug: 2021-08-17-intror-inmet
draft: no
event: Curso en el Instituto Nacional de Medicina Tropical (INMeT)
event_url: https://introduccionalr.netlify.app/
location: Online
abstract: |
all_day: no
publishDate: "`r Sys.Date()`"
featured: yes
links:
- icon: youtube
  icon_pack: fab
  name: videos
  url: https://www.youtube.com/playlist?list=PLHrlbDXyq3fGHiyqDjXCdWhF6TlTY6U4E
- icon: images
  icon_pack: fas
  name: slides
  url: https://introduccionalr.netlify.app/
---

## Descripción

Este es un curso de un mes y medio en programación R para análisis de datos biológicos. Se realiza de forma virtual y contará con una combinación de clases sincrónicas y asincrónicas, con ejercicios que se entregarán semanalmente y una presentación final. Es un curso intensivo y desafiante que invita al estudiante a pensar y desarrollar algoritmos para el análisis de datos biológicos. Específicamente, el curso tiene como objetivo enseñar a los participantes a:

(a) desarrollar e interpretar scripts R

(b) importar y manipular datos

(c) describir y visualizar datos

(d) crear informes con RMarkdown

Subiremos los videos de las clases al canal de youtube @somaquadrados. Los videos se pueden ver de forma asincrónica. El material escrito, diapositivas, scripts y tareas estarán disponibles en el repositorio de “Soma dos Quadrados”. Las clases sincrónicas se llevan a cabo semanalmente los viernes, de 2:00 pm a 5:00 pm y se utilizarán para resolver dudas y ejercicios.

El curso se ofrece de forma gratuita y la preinscripción estará abierta entre los días 12 y 31 de julio. El curso comienza el día 16 de agosto hasta el dia 27 de septiembre de 2021.

